# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 537)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_settimgs = QtWidgets.QWidget()
        self.tab_settimgs.setObjectName("tab_settimgs")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_settimgs)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableSetting = QtWidgets.QTableWidget(self.tab_settimgs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableSetting.sizePolicy().hasHeightForWidth())
        self.tableSetting.setSizePolicy(sizePolicy)
        self.tableSetting.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableSetting.setAutoScroll(True)
        self.tableSetting.setTabKeyNavigation(True)
        self.tableSetting.setDragEnabled(False)
        self.tableSetting.setShowGrid(True)
        self.tableSetting.setGridStyle(QtCore.Qt.SolidLine)
        self.tableSetting.setWordWrap(True)
        self.tableSetting.setCornerButtonEnabled(True)
        self.tableSetting.setRowCount(0)
        self.tableSetting.setColumnCount(0)
        self.tableSetting.setObjectName("tableSetting")
        self.tableSetting.horizontalHeader().setVisible(True)
        self.tableSetting.horizontalHeader().setCascadingSectionResizes(False)
        self.tableSetting.horizontalHeader().setHighlightSections(True)
        self.tableSetting.horizontalHeader().setMinimumSectionSize(51)
        self.tableSetting.horizontalHeader().setSortIndicatorShown(False)
        self.tableSetting.horizontalHeader().setStretchLastSection(False)
        self.tableSetting.verticalHeader().setVisible(True)
        self.tableSetting.verticalHeader().setCascadingSectionResizes(False)
        self.tableSetting.verticalHeader().setHighlightSections(True)
        self.tableSetting.verticalHeader().setSortIndicatorShown(False)
        self.tableSetting.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_2.addWidget(self.tableSetting)
        self.tabWidget.addTab(self.tab_settimgs, "")
        self.tab_phrase = QtWidgets.QWidget()
        self.tab_phrase.setObjectName("tab_phrase")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_phrase)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tablePhrase = QtWidgets.QTableWidget(self.tab_phrase)
        self.tablePhrase.setObjectName("tablePhrase")
        self.tablePhrase.setColumnCount(0)
        self.tablePhrase.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.tablePhrase)
        self.tabWidget.addTab(self.tab_phrase, "")
        self.tab_chat = QtWidgets.QWidget()
        self.tab_chat.setObjectName("tab_chat")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_chat)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.chatTextEdit = QtWidgets.QPlainTextEdit(self.tab_chat)
        self.chatTextEdit.setReadOnly(True)
        self.chatTextEdit.setObjectName("chatTextEdit")
        self.horizontalLayout_4.addWidget(self.chatTextEdit)
        self.tabWidget.addTab(self.tab_chat, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 722, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Старт"))
        self.stopButton.setText(_translate("MainWindow", "Стоп"))
        self.tableSetting.setSortingEnabled(False)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settimgs), _translate("MainWindow", "Настройки"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_phrase), _translate("MainWindow", "Фразы"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_chat), _translate("MainWindow", "Чат"))

